name: Create Artifact
on:
  push: {}
  release:
    types:
      - created

jobs:

  build-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build . --file Dockerfile --tag coqjit
      - name: Test
        run: docker run coqjit
      - name: Login
        env:
          QUAY_PW: ${{ secrets.QUAY_PW }}
        if: ${{ github.event_name == 'release' }}
        run: echo $QUAY_PW | docker login quay.io -u corejit --password-stdin
      - name: Push
        if: ${{ github.event_name == 'release' }}
        run: docker tag coqjit quay.io/corejit/jit:${{ github.sha }} && docker push quay.io/corejit/jit:${{ github.sha }}
